
# Server properties
server:
  port: 5001


# Database properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cognizant_fse
    username: root
    password: pass@word1

# Hibernate properties
  jpa:
    how-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


